POST http://localhost:80/api/auth/token
Content-Type: application/json

{
  "email": "test@example.org",
  "password": "testpassword123!"
}

###

POST http://localhost:80/api/auth/identity
Content-Type: application/json

{
  "email": "test@example.org",
  "password": "testpassword123!",
  "passwordConfirmation": "testpassword123!"
}

###
