// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package postgresql

import (
	"time"

	"github.com/google/uuid"
)

type Identity struct {
	ID        uuid.UUID
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
