apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Chart.Name }}-db-migrate"
  annotations:
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/resource-policy": keep
spec:
  template:
    spec:
      containers:
        - name: db-migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ['sh', '-c', 'make migrate']
restartPolicy: Never
backoffLimit: 10
